image: golang:1.8.3
stages:
  - compile
  - build
services:
    - docker:dind  

before_script:
  - mkdir -p /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/
  - cp -r /builds/vice/vice-api /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/
  - cd /go/src/omi-gitlab.e-technik.uni-ulm.de/vice/vice-api

compile:
  stage: compile
  script:
    - go get -d -v ./...
    - go build -v
    - cp vice-api /builds/vice/vice-api/
  artifacts:
    paths:
      - vice-api
      
build:
    stage: build
    image: docker:latest
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest    