#!/bin/bash

#save paths
currentpath=$(pwd)
[ -n "${GOPATH}" ] || export GOPATH=$(cd ../../../../; pwd)

# compile go app
cd $GOPATH
go build github.com/vice-registry/vice-api
mv vice-api $currentpath
cd $currentpath

# create docker image
docker build -t vice-api .
rm vice-api

# overwrite dockerhub image
#docker tag vice-api:latest viceregistry/vice-api:latest

# upload docker image
# todo

