swagger: '2.0'
info:
  title: ViCE Image Registry
  description: "API endpoint of the ViCE Image Registry: search, deploy, and import virtual environments from supported execution environments like OpenStack, Docker, or bwLehrpool."
  version: "0.1"
  contact:
    name: christopher.hauser@uni-ulm.de
host: localhost:8080
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /environments:
    get:
      summary: List by user accessible execution environments
      operationId: findEnvironment
      parameters:
        - name: filterManagementlayer
          in: query
          required: false
          type: string
        - name: filterRuntimetechnology
          in: query
          required: false
          type: string
      responses:
        200:
          description: An array of accessible execution environments.
          schema:
            type: array
            items:
              $ref: '#/definitions/Environment'
        401:
          $ref: "#/responses/UnauthorizedError"          
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []
          
    post:
      summary: Create a new execution environment for authenticated user
      operationId: createEnvironment
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: "#/definitions/Environment"
      consumes:
        - application/json
        - application/xml
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Environment"      
        401:
          $ref: "#/responses/UnauthorizedError"         
        405:
          description: Invalid input          
        500:  
          description: Internal Server Error    
      security:
        - vice_auth: []

    put:
      summary: Update an existing execution environment
      operationId: updateEnvironment
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: "#/definitions/Environment"
      consumes:
        - application/json
        - application/xml
      responses:
        201:
          description: Updated
          schema:
            $ref: "#/definitions/Environment"            
        401:
          $ref: "#/responses/UnauthorizedError"
        405:
          description: Invalid input
        404:
          description: Element not found
        500:  
          description: Internal Server Error     
      security:
        - vice_auth: []    
          
  /environment/{environmentId}:
    get:
      summary: Get execution environment by id
      operationId: getEnvironment
      parameters:
        - in: path
          name: environmentId
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Environment"
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Element not found
        500:  
          description: Internal Server Error  
      security:
        - vice_auth: []    

    delete:
      summary: Deletes an execution environment
      description: ""
      operationId: deleteEnvironment
      parameters:
        - in: path
          name: environmentId
          required: true
          type: string
      responses:
        200:
          description: successful operation      
        404:
          description: Element not found
        401:
          $ref: "#/responses/UnauthorizedError"          
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []

  /images:
    get:
      summary: List available images
      operationId: findImages
      responses:
        200:
          description: An array of images.
          schema:
            type: array
            items:
              $ref: '#/definitions/Image'
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []          

    post:
      summary: Create a new image
      operationId: createImage
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Image"
      consumes:
        - application/json
        - application/xml
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Image"      
        401:
          $ref: "#/responses/UnauthorizedError"          
        405:
          description: Invalid input          
        500:  
          description: Internal Server Error          
      security:
        - vice_auth: []
        
    put:
      summary: Update an existing image
      operationId: updateImage
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Image"
      consumes:
        - application/json
        - application/xml
      responses:
        201:
          description: Updated
          schema:
            $ref: "#/definitions/Image"            
        401:
          $ref: "#/responses/UnauthorizedError"
        405:
          description: Invalid input
        404:
          description: Element not found
        500:  
          description: Internal Server Error     
      security:
        - vice_auth: []

  /image/{imageId}:
    get:
      summary: Get an image by id
      operationId: getImage
      parameters:
        - in: path
          name: imageId
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Image"
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Element not found
        500:  
          description: Internal Server Error            
      security:
        - vice_auth: []    
        
    delete:
      summary: Deletes an image
      description: ""
      operationId: deleteImage
      parameters:
        - in: path
          name: imageId
          required: true
          type: string
      responses:
        200:
          description: successful operation      
        404:
          description: Element not found
        401:
          $ref: "#/responses/UnauthorizedError"          
        500:  
          description: Internal Server Error         
      security:
        - vice_auth: []

  /image/{imageId}/file:
    post:
      summary: Upload a file as image
      operationId: uploadImage
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
        - in: path
          name: imageId
          required: true
          type: string          
      responses:
        200:
          description: successful operation
        400:
          description:  Bad request
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Element not found
        500:  
          description: Internal Server Error            
      security:
        - vice_auth: []
    get:
      summary: Download a file as image
      operationId: downloadImage
      parameters:
        - in: path
          name: imageId
          required: true
          type: string      
      produces:
        - application/octet
      responses:
        200:
          description: successful operation
          schema:
            type: file          
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Element not found
        500:  
          description: Internal Server Error            
      security:
        - vice_auth: []          

  /deploy:
    post:
      summary: Create an image into an environment
      operationId: deployImage
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Deployment"
      consumes:
        - application/json
        - application/xml
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Deployment"      
        401:
          $ref: "#/responses/UnauthorizedError"         
        405:
          description: Invalid input          
        500:  
          description: Internal Server Error           
      security:
        - vice_auth: []

  /deployments:
    get:
      summary: List all deployments of authenticated user
      operationId: findDeployments
      responses:
        200:
          description: An array of deployments.
          schema:
            type: array
            items:
              $ref: '#/definitions/Deployment'
        401:
          $ref: "#/responses/UnauthorizedError"            
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []
        
  /deployment/{deploymentId}:
    get:
      summary: Get a deployment
      operationId: getDeployment
      parameters:
        - in: path
          name: deploymentId
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Deployment"
        401:
          $ref: "#/responses/UnauthorizedError"             
        404:
          description: Deployment not found
        500:  
          description: Internal Server Error         
      security:
        - vice_auth: []    

    delete:
      summary: Removes an image deployment from the environment
      description: ""
      operationId: deleteDeployment
      parameters:
        - in: path
          name: deploymentId
          required: true
          type: string
      responses:
        200:
          description: successful operation      
        404:
          description: Element not found
        401:
          $ref: "#/responses/UnauthorizedError"          
        500:  
          description: Internal Server Error   
      security:
        - vice_auth: []

  /runtimestats:
    get:
      summary: Provide internal statistics about import/export queue length and workers
      operationId: getRuntimeStats
      responses:
        200:
          description: successful operation
          schema:        
            $ref: "#/definitions/RuntimeStats"
        401:
          $ref: "#/responses/UnauthorizedError"
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []

  /user:
    get:
      summary: Provide user information about logged in user
      operationId: getUser
      responses:
        200:
          description: successful operation
          schema:        
            $ref: "#/definitions/User"
        401:
          $ref: "#/responses/UnauthorizedError"
        500:  
          description: Internal Server Error
      security:
        - vice_auth: []
    post:
      summary: Create a new user in the system
      operationId: createUser
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/User"
      consumes:
        - application/json
        - application/xml      
      responses:
        200:
          description: successful operation
          schema:        
            $ref: "#/definitions/User"
        401:
          $ref: "#/responses/UnauthorizedError"
        500:  
          description: Internal Server Error


securityDefinitions:
  vice_auth:
    type: basic

definitions:
  Environment:
    properties:
      id:
        type: string    
      title:
        type: string            
      userid:
        type: string
      credentials:
        $ref: "#/definitions/Credentials"
      runtimetechnology:
        $ref: "#/definitions/RuntimeTechnology"
      managementlayer:
        $ref: "#/definitions/ManagementLayer"
  Credentials:
    type: object
    properties:
      location:
        type: string
      username:
        type: string
      password:
        type: string
      specifics:
        type: object
  RuntimeTechnology:
    type: object
    properties:
      type:
        type: string
        enum: [virtualmachine, container, application]
      software:
        type: string
      version:
        type: string
  ManagementLayer:
    type: object
    properties:
      type:
        type: string
        enum: [basic, cloudcomputing, containercluster, jobscheduler]
      software:
        type: string
      version:
        type: string

  User:
    properties:
      id:
        type: string    
      username:
        type: string
      password:
        type: string
      email:
        type: string
      fullname:
        type: string

  Image:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      userid:
        type: string
      imagetype:
        type: string
        enum: [implicit, declarative]
      contenttype:
        type: string
        enum: [disk-raw, disk-qcow2, disk-vmdk, docker-file, docker-image, packerfile]
      imported:
        type: boolean
      originEnvironment:
        $ref: "#/definitions/Environment"
      environmentReference:
        type: string
      specifics:
        type: object

  Deployment:
    type: object
    properties:
      id:
        type: string
      title:
        type: string        
      userid:
        type: string
      imageid:
        type: string
      environmentId:
        type: string
      environmentReference:
        type: string

  RuntimeStats:
    properties:
      importsPending:
        type: integer
      importWorker:
        type: integer
      exportsPending:
        type: integer
      exportWorker:
        type: integer
      storePending:
        type: integer
      storeWorker:
        type: integer

responses:
  UnauthorizedError:
    description: Authentication information is missing or invalid
    headers:
      WWW_Authenticate:
        type: string