#!/bin/bash
#
# Description:
# swagger-gen generates the go source gode from the swagger.yaml
# This script is a wrapper for the swagger command line tool, where 
# parameters like GOPATH are set correctly.
#
# Author: Christopher Hauser <post@c-ha.de>
#

command -v swagger >/dev/null 2>&1 || { echo >&2 "Swagger is not installed.  Aborting."; exit 1; }

export GOPATH=$(cd ../../../../; pwd)
echo "Selecting gopath as: $GOPATH"

# export models
swagger generate server -A vice-api -f swagger.yaml --principal models.User --model-package=models --target=../vice-util/ --skip-operations --skip-support

# export rest server
swagger generate server -A vice-api -f swagger.yaml --principal models.User --skip-models --existing-models=github.com/vice-registry/vice-util/models

# remove generated main.go, we will work with a copy...
rm cmd/vice-server/main.go -r
rm cmd/ -r

# export typescript-angular2 services and models
java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l typescript-angular2 -o ../vice-webui/src/app/api/

# export API docs
java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l html -o ../vice-registry/docs/api/

