#!/bin/bash
#
# Description:
# swagger-gen generates the go source gode from the swagger.yaml
# This script is a wrapper for the swagger command line tool, where 
# parameters like GOPATH are set correctly.
#
# Author: Christopher Hauser <post@c-ha.de>
#

command -v swagger >/dev/null 2>&1 || { echo >&2 "Swagger is not installed.  Aborting."; exit 1; }

export GOPATH=$(cd ../../../../; pwd)
echo "Selecting gopath as: $GOPATH"
swagger generate server -A vice-api -f swagger.yaml

# remove generated main.go, we will work with a copy...
rm cmd/vice-server/main.go -r