package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateExecutionEnvironmentMethodNotAllowedCode is the HTTP code returned for type CreateExecutionEnvironmentMethodNotAllowed
const CreateExecutionEnvironmentMethodNotAllowedCode int = 405

/*CreateExecutionEnvironmentMethodNotAllowed Invalid input

swagger:response createExecutionEnvironmentMethodNotAllowed
*/
type CreateExecutionEnvironmentMethodNotAllowed struct {
}

// NewCreateExecutionEnvironmentMethodNotAllowed creates CreateExecutionEnvironmentMethodNotAllowed with default headers values
func NewCreateExecutionEnvironmentMethodNotAllowed() *CreateExecutionEnvironmentMethodNotAllowed {
	return &CreateExecutionEnvironmentMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateExecutionEnvironmentMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
