package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"omi-gitlab.e-technik.uni-ulm.de/vice/vice-api/models"
)

// CreateEnvironmentHandlerFunc turns a function with the right signature into a create environment handler
type CreateEnvironmentHandlerFunc func(CreateEnvironmentParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateEnvironmentHandlerFunc) Handle(params CreateEnvironmentParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateEnvironmentHandler interface for that can handle valid create environment params
type CreateEnvironmentHandler interface {
	Handle(CreateEnvironmentParams, *models.User) middleware.Responder
}

// NewCreateEnvironment creates a new http.Handler for the create environment operation
func NewCreateEnvironment(ctx *middleware.Context, handler CreateEnvironmentHandler) *CreateEnvironment {
	return &CreateEnvironment{Context: ctx, Handler: handler}
}

/*CreateEnvironment swagger:route POST /environments createEnvironment

Create a new execution environment for authenticated user

*/
type CreateEnvironment struct {
	Context *middleware.Context
	Handler CreateEnvironmentHandler
}

func (o *CreateEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
