// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vice-registry/vice-api/models"
)

// CreateImageCreatedCode is the HTTP code returned for type CreateImageCreated
const CreateImageCreatedCode int = 201

/*CreateImageCreated Created

swagger:response createImageCreated
*/
type CreateImageCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Image `json:"body,omitempty"`
}

// NewCreateImageCreated creates CreateImageCreated with default headers values
func NewCreateImageCreated() *CreateImageCreated {
	return &CreateImageCreated{}
}

// WithPayload adds the payload to the create image created response
func (o *CreateImageCreated) WithPayload(payload *models.Image) *CreateImageCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create image created response
func (o *CreateImageCreated) SetPayload(payload *models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateImageCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateImageUnauthorizedCode is the HTTP code returned for type CreateImageUnauthorized
const CreateImageUnauthorizedCode int = 401

/*CreateImageUnauthorized Authentication information is missing or invalid

swagger:response createImageUnauthorized
*/
type CreateImageUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewCreateImageUnauthorized creates CreateImageUnauthorized with default headers values
func NewCreateImageUnauthorized() *CreateImageUnauthorized {
	return &CreateImageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the create image unauthorized response
func (o *CreateImageUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *CreateImageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the create image unauthorized response
func (o *CreateImageUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *CreateImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// CreateImageMethodNotAllowedCode is the HTTP code returned for type CreateImageMethodNotAllowed
const CreateImageMethodNotAllowedCode int = 405

/*CreateImageMethodNotAllowed Invalid input

swagger:response createImageMethodNotAllowed
*/
type CreateImageMethodNotAllowed struct {
}

// NewCreateImageMethodNotAllowed creates CreateImageMethodNotAllowed with default headers values
func NewCreateImageMethodNotAllowed() *CreateImageMethodNotAllowed {
	return &CreateImageMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateImageMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}

// CreateImageInternalServerErrorCode is the HTTP code returned for type CreateImageInternalServerError
const CreateImageInternalServerErrorCode int = 500

/*CreateImageInternalServerError Internal Server Error

swagger:response createImageInternalServerError
*/
type CreateImageInternalServerError struct {
}

// NewCreateImageInternalServerError creates CreateImageInternalServerError with default headers values
func NewCreateImageInternalServerError() *CreateImageInternalServerError {
	return &CreateImageInternalServerError{}
}

// WriteResponse to the client
func (o *CreateImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
