package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-api/models"
)

// CreateImageHandlerFunc turns a function with the right signature into a create image handler
type CreateImageHandlerFunc func(CreateImageParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateImageHandlerFunc) Handle(params CreateImageParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateImageHandler interface for that can handle valid create image params
type CreateImageHandler interface {
	Handle(CreateImageParams, *models.User) middleware.Responder
}

// NewCreateImage creates a new http.Handler for the create image operation
func NewCreateImage(ctx *middleware.Context, handler CreateImageHandler) *CreateImage {
	return &CreateImage{Context: ctx, Handler: handler}
}

/*CreateImage swagger:route POST /images createImage

Create a new image

*/
type CreateImage struct {
	Context *middleware.Context
	Handler CreateImageHandler
}

func (o *CreateImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateImageParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
