package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateExecutionEnvironmentHandlerFunc turns a function with the right signature into a create execution environment handler
type CreateExecutionEnvironmentHandlerFunc func(CreateExecutionEnvironmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateExecutionEnvironmentHandlerFunc) Handle(params CreateExecutionEnvironmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateExecutionEnvironmentHandler interface for that can handle valid create execution environment params
type CreateExecutionEnvironmentHandler interface {
	Handle(CreateExecutionEnvironmentParams, interface{}) middleware.Responder
}

// NewCreateExecutionEnvironment creates a new http.Handler for the create execution environment operation
func NewCreateExecutionEnvironment(ctx *middleware.Context, handler CreateExecutionEnvironmentHandler) *CreateExecutionEnvironment {
	return &CreateExecutionEnvironment{Context: ctx, Handler: handler}
}

/*CreateExecutionEnvironment swagger:route POST /executionenvironments createExecutionEnvironment

Create a new execution environment for authenticated user

*/
type CreateExecutionEnvironment struct {
	Context *middleware.Context
	Handler CreateExecutionEnvironmentHandler
}

func (o *CreateExecutionEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateExecutionEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
