package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteExecutionEnvironmentBadRequestCode is the HTTP code returned for type DeleteExecutionEnvironmentBadRequest
const DeleteExecutionEnvironmentBadRequestCode int = 400

/*DeleteExecutionEnvironmentBadRequest Invalid ID supplied

swagger:response deleteExecutionEnvironmentBadRequest
*/
type DeleteExecutionEnvironmentBadRequest struct {
}

// NewDeleteExecutionEnvironmentBadRequest creates DeleteExecutionEnvironmentBadRequest with default headers values
func NewDeleteExecutionEnvironmentBadRequest() *DeleteExecutionEnvironmentBadRequest {
	return &DeleteExecutionEnvironmentBadRequest{}
}

// WriteResponse to the client
func (o *DeleteExecutionEnvironmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
