package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteImageHandlerFunc turns a function with the right signature into a delete image handler
type DeleteImageHandlerFunc func(DeleteImageParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteImageHandlerFunc) Handle(params DeleteImageParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteImageHandler interface for that can handle valid delete image params
type DeleteImageHandler interface {
	Handle(DeleteImageParams, interface{}) middleware.Responder
}

// NewDeleteImage creates a new http.Handler for the delete image operation
func NewDeleteImage(ctx *middleware.Context, handler DeleteImageHandler) *DeleteImage {
	return &DeleteImage{Context: ctx, Handler: handler}
}

/*DeleteImage swagger:route DELETE /image/{imageId} deleteImage

Deletes an image

*/
type DeleteImage struct {
	Context *middleware.Context
	Handler DeleteImageHandler
}

func (o *DeleteImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDeleteImageParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
