package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteImageOKCode is the HTTP code returned for type DeleteImageOK
const DeleteImageOKCode int = 200

/*DeleteImageOK successful operation

swagger:response deleteImageOK
*/
type DeleteImageOK struct {
}

// NewDeleteImageOK creates DeleteImageOK with default headers values
func NewDeleteImageOK() *DeleteImageOK {
	return &DeleteImageOK{}
}

// WriteResponse to the client
func (o *DeleteImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteImageBadRequestCode is the HTTP code returned for type DeleteImageBadRequest
const DeleteImageBadRequestCode int = 400

/*DeleteImageBadRequest Invalid ID supplied

swagger:response deleteImageBadRequest
*/
type DeleteImageBadRequest struct {
}

// NewDeleteImageBadRequest creates DeleteImageBadRequest with default headers values
func NewDeleteImageBadRequest() *DeleteImageBadRequest {
	return &DeleteImageBadRequest{}
}

// WriteResponse to the client
func (o *DeleteImageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DeleteImageUnauthorizedCode is the HTTP code returned for type DeleteImageUnauthorized
const DeleteImageUnauthorizedCode int = 401

/*DeleteImageUnauthorized Authentication information is missing or invalid

swagger:response deleteImageUnauthorized
*/
type DeleteImageUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteImageUnauthorized creates DeleteImageUnauthorized with default headers values
func NewDeleteImageUnauthorized() *DeleteImageUnauthorized {
	return &DeleteImageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete image unauthorized response
func (o *DeleteImageUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteImageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete image unauthorized response
func (o *DeleteImageUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}
