// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentParams creates a new DeleteEnvironmentParams object
// with the default values initialized.
func NewDeleteEnvironmentParams() DeleteEnvironmentParams {
	var ()
	return DeleteEnvironmentParams{}
}

// DeleteEnvironmentParams contains all the bound params for the delete environment operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteEnvironment
type DeleteEnvironmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	EnvironmentID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteEnvironmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rEnvironmentID, rhkEnvironmentID, _ := route.Params.GetOK("environmentId")
	if err := o.bindEnvironmentID(rEnvironmentID, rhkEnvironmentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteEnvironmentParams) bindEnvironmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.EnvironmentID = raw

	return nil
}
