package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteImageOKCode is the HTTP code returned for type DeleteImageOK
const DeleteImageOKCode int = 200

/*DeleteImageOK successful operation

swagger:response deleteImageOK
*/
type DeleteImageOK struct {
}

// NewDeleteImageOK creates DeleteImageOK with default headers values
func NewDeleteImageOK() *DeleteImageOK {
	return &DeleteImageOK{}
}

// WriteResponse to the client
func (o *DeleteImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteImageUnauthorizedCode is the HTTP code returned for type DeleteImageUnauthorized
const DeleteImageUnauthorizedCode int = 401

/*DeleteImageUnauthorized Authentication information is missing or invalid

swagger:response deleteImageUnauthorized
*/
type DeleteImageUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteImageUnauthorized creates DeleteImageUnauthorized with default headers values
func NewDeleteImageUnauthorized() *DeleteImageUnauthorized {
	return &DeleteImageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete image unauthorized response
func (o *DeleteImageUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteImageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete image unauthorized response
func (o *DeleteImageUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// DeleteImageNotFoundCode is the HTTP code returned for type DeleteImageNotFound
const DeleteImageNotFoundCode int = 404

/*DeleteImageNotFound Element not found

swagger:response deleteImageNotFound
*/
type DeleteImageNotFound struct {
}

// NewDeleteImageNotFound creates DeleteImageNotFound with default headers values
func NewDeleteImageNotFound() *DeleteImageNotFound {
	return &DeleteImageNotFound{}
}

// WriteResponse to the client
func (o *DeleteImageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DeleteImageInternalServerErrorCode is the HTTP code returned for type DeleteImageInternalServerError
const DeleteImageInternalServerErrorCode int = 500

/*DeleteImageInternalServerError Internal Server Error

swagger:response deleteImageInternalServerError
*/
type DeleteImageInternalServerError struct {
}

// NewDeleteImageInternalServerError creates DeleteImageInternalServerError with default headers values
func NewDeleteImageInternalServerError() *DeleteImageInternalServerError {
	return &DeleteImageInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
