// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteEnvironmentOKCode is the HTTP code returned for type DeleteEnvironmentOK
const DeleteEnvironmentOKCode int = 200

/*DeleteEnvironmentOK successful operation

swagger:response deleteEnvironmentOK
*/
type DeleteEnvironmentOK struct {
}

// NewDeleteEnvironmentOK creates DeleteEnvironmentOK with default headers values
func NewDeleteEnvironmentOK() *DeleteEnvironmentOK {
	return &DeleteEnvironmentOK{}
}

// WriteResponse to the client
func (o *DeleteEnvironmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteEnvironmentUnauthorizedCode is the HTTP code returned for type DeleteEnvironmentUnauthorized
const DeleteEnvironmentUnauthorizedCode int = 401

/*DeleteEnvironmentUnauthorized Authentication information is missing or invalid

swagger:response deleteEnvironmentUnauthorized
*/
type DeleteEnvironmentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteEnvironmentUnauthorized creates DeleteEnvironmentUnauthorized with default headers values
func NewDeleteEnvironmentUnauthorized() *DeleteEnvironmentUnauthorized {
	return &DeleteEnvironmentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete environment unauthorized response
func (o *DeleteEnvironmentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteEnvironmentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete environment unauthorized response
func (o *DeleteEnvironmentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteEnvironmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// DeleteEnvironmentNotFoundCode is the HTTP code returned for type DeleteEnvironmentNotFound
const DeleteEnvironmentNotFoundCode int = 404

/*DeleteEnvironmentNotFound Element not found

swagger:response deleteEnvironmentNotFound
*/
type DeleteEnvironmentNotFound struct {
}

// NewDeleteEnvironmentNotFound creates DeleteEnvironmentNotFound with default headers values
func NewDeleteEnvironmentNotFound() *DeleteEnvironmentNotFound {
	return &DeleteEnvironmentNotFound{}
}

// WriteResponse to the client
func (o *DeleteEnvironmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DeleteEnvironmentInternalServerErrorCode is the HTTP code returned for type DeleteEnvironmentInternalServerError
const DeleteEnvironmentInternalServerErrorCode int = 500

/*DeleteEnvironmentInternalServerError Internal Server Error

swagger:response deleteEnvironmentInternalServerError
*/
type DeleteEnvironmentInternalServerError struct {
}

// NewDeleteEnvironmentInternalServerError creates DeleteEnvironmentInternalServerError with default headers values
func NewDeleteEnvironmentInternalServerError() *DeleteEnvironmentInternalServerError {
	return &DeleteEnvironmentInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteEnvironmentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
