// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDeploymentOKCode is the HTTP code returned for type DeleteDeploymentOK
const DeleteDeploymentOKCode int = 200

/*DeleteDeploymentOK successful operation

swagger:response deleteDeploymentOK
*/
type DeleteDeploymentOK struct {
}

// NewDeleteDeploymentOK creates DeleteDeploymentOK with default headers values
func NewDeleteDeploymentOK() *DeleteDeploymentOK {
	return &DeleteDeploymentOK{}
}

// WriteResponse to the client
func (o *DeleteDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteDeploymentUnauthorizedCode is the HTTP code returned for type DeleteDeploymentUnauthorized
const DeleteDeploymentUnauthorizedCode int = 401

/*DeleteDeploymentUnauthorized Authentication information is missing or invalid

swagger:response deleteDeploymentUnauthorized
*/
type DeleteDeploymentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteDeploymentUnauthorized creates DeleteDeploymentUnauthorized with default headers values
func NewDeleteDeploymentUnauthorized() *DeleteDeploymentUnauthorized {
	return &DeleteDeploymentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete deployment unauthorized response
func (o *DeleteDeploymentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteDeploymentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete deployment unauthorized response
func (o *DeleteDeploymentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteDeploymentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// DeleteDeploymentNotFoundCode is the HTTP code returned for type DeleteDeploymentNotFound
const DeleteDeploymentNotFoundCode int = 404

/*DeleteDeploymentNotFound Element not found

swagger:response deleteDeploymentNotFound
*/
type DeleteDeploymentNotFound struct {
}

// NewDeleteDeploymentNotFound creates DeleteDeploymentNotFound with default headers values
func NewDeleteDeploymentNotFound() *DeleteDeploymentNotFound {
	return &DeleteDeploymentNotFound{}
}

// WriteResponse to the client
func (o *DeleteDeploymentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DeleteDeploymentInternalServerErrorCode is the HTTP code returned for type DeleteDeploymentInternalServerError
const DeleteDeploymentInternalServerErrorCode int = 500

/*DeleteDeploymentInternalServerError Internal Server Error

swagger:response deleteDeploymentInternalServerError
*/
type DeleteDeploymentInternalServerError struct {
}

// NewDeleteDeploymentInternalServerError creates DeleteDeploymentInternalServerError with default headers values
func NewDeleteDeploymentInternalServerError() *DeleteDeploymentInternalServerError {
	return &DeleteDeploymentInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteDeploymentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
