package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vice-registry/vice-api/models"
)

// DeployImageCreatedCode is the HTTP code returned for type DeployImageCreated
const DeployImageCreatedCode int = 201

/*DeployImageCreated Created

swagger:response deployImageCreated
*/
type DeployImageCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Deployment `json:"body,omitempty"`
}

// NewDeployImageCreated creates DeployImageCreated with default headers values
func NewDeployImageCreated() *DeployImageCreated {
	return &DeployImageCreated{}
}

// WithPayload adds the payload to the deploy image created response
func (o *DeployImageCreated) WithPayload(payload *models.Deployment) *DeployImageCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deploy image created response
func (o *DeployImageCreated) SetPayload(payload *models.Deployment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeployImageCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeployImageUnauthorizedCode is the HTTP code returned for type DeployImageUnauthorized
const DeployImageUnauthorizedCode int = 401

/*DeployImageUnauthorized Authentication information is missing or invalid

swagger:response deployImageUnauthorized
*/
type DeployImageUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeployImageUnauthorized creates DeployImageUnauthorized with default headers values
func NewDeployImageUnauthorized() *DeployImageUnauthorized {
	return &DeployImageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the deploy image unauthorized response
func (o *DeployImageUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeployImageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the deploy image unauthorized response
func (o *DeployImageUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeployImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// DeployImageMethodNotAllowedCode is the HTTP code returned for type DeployImageMethodNotAllowed
const DeployImageMethodNotAllowedCode int = 405

/*DeployImageMethodNotAllowed Invalid input

swagger:response deployImageMethodNotAllowed
*/
type DeployImageMethodNotAllowed struct {
}

// NewDeployImageMethodNotAllowed creates DeployImageMethodNotAllowed with default headers values
func NewDeployImageMethodNotAllowed() *DeployImageMethodNotAllowed {
	return &DeployImageMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeployImageMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}

// DeployImageInternalServerErrorCode is the HTTP code returned for type DeployImageInternalServerError
const DeployImageInternalServerErrorCode int = 500

/*DeployImageInternalServerError Internal Server Error

swagger:response deployImageInternalServerError
*/
type DeployImageInternalServerError struct {
}

// NewDeployImageInternalServerError creates DeployImageInternalServerError with default headers values
func NewDeployImageInternalServerError() *DeployImageInternalServerError {
	return &DeployImageInternalServerError{}
}

// WriteResponse to the client
func (o *DeployImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
