// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadImageOKCode is the HTTP code returned for type DownloadImageOK
const DownloadImageOKCode int = 200

/*DownloadImageOK successful operation

swagger:response downloadImageOK
*/
type DownloadImageOK struct {

	/*
	  In: Body
	*/
	Payload runtime.File `json:"body,omitempty"`
}

// NewDownloadImageOK creates DownloadImageOK with default headers values
func NewDownloadImageOK() *DownloadImageOK {
	return &DownloadImageOK{}
}

// WithPayload adds the payload to the download image o k response
func (o *DownloadImageOK) WithPayload(payload runtime.File) *DownloadImageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download image o k response
func (o *DownloadImageOK) SetPayload(payload runtime.File) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DownloadImageUnauthorizedCode is the HTTP code returned for type DownloadImageUnauthorized
const DownloadImageUnauthorizedCode int = 401

/*DownloadImageUnauthorized Authentication information is missing or invalid

swagger:response downloadImageUnauthorized
*/
type DownloadImageUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDownloadImageUnauthorized creates DownloadImageUnauthorized with default headers values
func NewDownloadImageUnauthorized() *DownloadImageUnauthorized {
	return &DownloadImageUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the download image unauthorized response
func (o *DownloadImageUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DownloadImageUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the download image unauthorized response
func (o *DownloadImageUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DownloadImageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// DownloadImageNotFoundCode is the HTTP code returned for type DownloadImageNotFound
const DownloadImageNotFoundCode int = 404

/*DownloadImageNotFound Element not found

swagger:response downloadImageNotFound
*/
type DownloadImageNotFound struct {
}

// NewDownloadImageNotFound creates DownloadImageNotFound with default headers values
func NewDownloadImageNotFound() *DownloadImageNotFound {
	return &DownloadImageNotFound{}
}

// WriteResponse to the client
func (o *DownloadImageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DownloadImageInternalServerErrorCode is the HTTP code returned for type DownloadImageInternalServerError
const DownloadImageInternalServerErrorCode int = 500

/*DownloadImageInternalServerError Internal Server Error

swagger:response downloadImageInternalServerError
*/
type DownloadImageInternalServerError struct {
}

// NewDownloadImageInternalServerError creates DownloadImageInternalServerError with default headers values
func NewDownloadImageInternalServerError() *DownloadImageInternalServerError {
	return &DownloadImageInternalServerError{}
}

// WriteResponse to the client
func (o *DownloadImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
