// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-util/models"
)

// DownloadImageHandlerFunc turns a function with the right signature into a download image handler
type DownloadImageHandlerFunc func(DownloadImageParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadImageHandlerFunc) Handle(params DownloadImageParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DownloadImageHandler interface for that can handle valid download image params
type DownloadImageHandler interface {
	Handle(DownloadImageParams, *models.User) middleware.Responder
}

// NewDownloadImage creates a new http.Handler for the download image operation
func NewDownloadImage(ctx *middleware.Context, handler DownloadImageHandler) *DownloadImage {
	return &DownloadImage{Context: ctx, Handler: handler}
}

/*DownloadImage swagger:route GET /image/{imageId}/file downloadImage

Download a file as image

*/
type DownloadImage struct {
	Context *middleware.Context
	Handler DownloadImageHandler
}

func (o *DownloadImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadImageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
