// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vice-registry/vice-api/models"
)

// FindImagesOKCode is the HTTP code returned for type FindImagesOK
const FindImagesOKCode int = 200

/*FindImagesOK An array of images.

swagger:response findImagesOK
*/
type FindImagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Image `json:"body,omitempty"`
}

// NewFindImagesOK creates FindImagesOK with default headers values
func NewFindImagesOK() *FindImagesOK {
	return &FindImagesOK{}
}

// WithPayload adds the payload to the find images o k response
func (o *FindImagesOK) WithPayload(payload []*models.Image) *FindImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find images o k response
func (o *FindImagesOK) SetPayload(payload []*models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Image, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindImagesInternalServerErrorCode is the HTTP code returned for type FindImagesInternalServerError
const FindImagesInternalServerErrorCode int = 500

/*FindImagesInternalServerError Internal Server Error

swagger:response findImagesInternalServerError
*/
type FindImagesInternalServerError struct {
}

// NewFindImagesInternalServerError creates FindImagesInternalServerError with default headers values
func NewFindImagesInternalServerError() *FindImagesInternalServerError {
	return &FindImagesInternalServerError{}
}

// WriteResponse to the client
func (o *FindImagesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
