package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-api/models"
)

// FindEnvironmentHandlerFunc turns a function with the right signature into a find environment handler
type FindEnvironmentHandlerFunc func(FindEnvironmentParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn FindEnvironmentHandlerFunc) Handle(params FindEnvironmentParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// FindEnvironmentHandler interface for that can handle valid find environment params
type FindEnvironmentHandler interface {
	Handle(FindEnvironmentParams, *models.User) middleware.Responder
}

// NewFindEnvironment creates a new http.Handler for the find environment operation
func NewFindEnvironment(ctx *middleware.Context, handler FindEnvironmentHandler) *FindEnvironment {
	return &FindEnvironment{Context: ctx, Handler: handler}
}

/*FindEnvironment swagger:route GET /environments findEnvironment

List by user accessible execution environments

*/
type FindEnvironment struct {
	Context *middleware.Context
	Handler FindEnvironmentHandler
}

func (o *FindEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewFindEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
