package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"omi-gitlab.e-technik.uni-ulm.de/vice/vice-api/models"
)

// FindImagesOKCode is the HTTP code returned for type FindImagesOK
const FindImagesOKCode int = 200

/*FindImagesOK An array of images.

swagger:response findImagesOK
*/
type FindImagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Image `json:"body,omitempty"`
}

// NewFindImagesOK creates FindImagesOK with default headers values
func NewFindImagesOK() *FindImagesOK {
	return &FindImagesOK{}
}

// WithPayload adds the payload to the find images o k response
func (o *FindImagesOK) WithPayload(payload []*models.Image) *FindImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find images o k response
func (o *FindImagesOK) SetPayload(payload []*models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Image, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindImagesDefault Unexpected error

swagger:response findImagesDefault
*/
type FindImagesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindImagesDefault creates FindImagesDefault with default headers values
func NewFindImagesDefault(code int) *FindImagesDefault {
	if code <= 0 {
		code = 500
	}

	return &FindImagesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find images default response
func (o *FindImagesDefault) WithStatusCode(code int) *FindImagesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find images default response
func (o *FindImagesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find images default response
func (o *FindImagesDefault) WithPayload(payload *models.Error) *FindImagesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find images default response
func (o *FindImagesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindImagesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
