package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindExecutionEnvironmentHandlerFunc turns a function with the right signature into a find execution environment handler
type FindExecutionEnvironmentHandlerFunc func(FindExecutionEnvironmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FindExecutionEnvironmentHandlerFunc) Handle(params FindExecutionEnvironmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FindExecutionEnvironmentHandler interface for that can handle valid find execution environment params
type FindExecutionEnvironmentHandler interface {
	Handle(FindExecutionEnvironmentParams, interface{}) middleware.Responder
}

// NewFindExecutionEnvironment creates a new http.Handler for the find execution environment operation
func NewFindExecutionEnvironment(ctx *middleware.Context, handler FindExecutionEnvironmentHandler) *FindExecutionEnvironment {
	return &FindExecutionEnvironment{Context: ctx, Handler: handler}
}

/*FindExecutionEnvironment swagger:route GET /executionenvironments findExecutionEnvironment

List by user accessible execution environments

*/
type FindExecutionEnvironment struct {
	Context *middleware.Context
	Handler FindExecutionEnvironmentHandler
}

func (o *FindExecutionEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewFindExecutionEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
