package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"omi-gitlab.e-technik.uni-ulm.de/vice/vice-api/models"
)

// FindEnvironmentOKCode is the HTTP code returned for type FindEnvironmentOK
const FindEnvironmentOKCode int = 200

/*FindEnvironmentOK An array of accessible execution environments.

swagger:response findEnvironmentOK
*/
type FindEnvironmentOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Environment `json:"body,omitempty"`
}

// NewFindEnvironmentOK creates FindEnvironmentOK with default headers values
func NewFindEnvironmentOK() *FindEnvironmentOK {
	return &FindEnvironmentOK{}
}

// WithPayload adds the payload to the find environment o k response
func (o *FindEnvironmentOK) WithPayload(payload []*models.Environment) *FindEnvironmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find environment o k response
func (o *FindEnvironmentOK) SetPayload(payload []*models.Environment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindEnvironmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Environment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindEnvironmentUnauthorizedCode is the HTTP code returned for type FindEnvironmentUnauthorized
const FindEnvironmentUnauthorizedCode int = 401

/*FindEnvironmentUnauthorized Authentication information is missing or invalid

swagger:response findEnvironmentUnauthorized
*/
type FindEnvironmentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewFindEnvironmentUnauthorized creates FindEnvironmentUnauthorized with default headers values
func NewFindEnvironmentUnauthorized() *FindEnvironmentUnauthorized {
	return &FindEnvironmentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the find environment unauthorized response
func (o *FindEnvironmentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *FindEnvironmentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the find environment unauthorized response
func (o *FindEnvironmentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *FindEnvironmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

/*FindEnvironmentDefault Unexpected error

swagger:response findEnvironmentDefault
*/
type FindEnvironmentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindEnvironmentDefault creates FindEnvironmentDefault with default headers values
func NewFindEnvironmentDefault(code int) *FindEnvironmentDefault {
	if code <= 0 {
		code = 500
	}

	return &FindEnvironmentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find environment default response
func (o *FindEnvironmentDefault) WithStatusCode(code int) *FindEnvironmentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find environment default response
func (o *FindEnvironmentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find environment default response
func (o *FindEnvironmentDefault) WithPayload(payload *models.Error) *FindEnvironmentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find environment default response
func (o *FindEnvironmentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindEnvironmentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
