package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindEnvironmentParams creates a new FindEnvironmentParams object
// with the default values initialized.
func NewFindEnvironmentParams() FindEnvironmentParams {
	var ()
	return FindEnvironmentParams{}
}

// FindEnvironmentParams contains all the bound params for the find environment operation
// typically these are obtained from a http.Request
//
// swagger:parameters findEnvironment
type FindEnvironmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: query
	*/
	FilterManagementlayer *string
	/*
	  In: query
	*/
	FilterRuntimetechnology *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindEnvironmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFilterManagementlayer, qhkFilterManagementlayer, _ := qs.GetOK("filterManagementlayer")
	if err := o.bindFilterManagementlayer(qFilterManagementlayer, qhkFilterManagementlayer, route.Formats); err != nil {
		res = append(res, err)
	}

	qFilterRuntimetechnology, qhkFilterRuntimetechnology, _ := qs.GetOK("filterRuntimetechnology")
	if err := o.bindFilterRuntimetechnology(qFilterRuntimetechnology, qhkFilterRuntimetechnology, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindEnvironmentParams) bindFilterManagementlayer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.FilterManagementlayer = &raw

	return nil
}

func (o *FindEnvironmentParams) bindFilterRuntimetechnology(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.FilterRuntimetechnology = &raw

	return nil
}
