package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vice-registry/vice-api/models"
)

// FindDeploymentsOKCode is the HTTP code returned for type FindDeploymentsOK
const FindDeploymentsOKCode int = 200

/*FindDeploymentsOK An array of deployments.

swagger:response findDeploymentsOK
*/
type FindDeploymentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Deployment `json:"body,omitempty"`
}

// NewFindDeploymentsOK creates FindDeploymentsOK with default headers values
func NewFindDeploymentsOK() *FindDeploymentsOK {
	return &FindDeploymentsOK{}
}

// WithPayload adds the payload to the find deployments o k response
func (o *FindDeploymentsOK) WithPayload(payload []*models.Deployment) *FindDeploymentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find deployments o k response
func (o *FindDeploymentsOK) SetPayload(payload []*models.Deployment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindDeploymentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Deployment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindDeploymentsUnauthorizedCode is the HTTP code returned for type FindDeploymentsUnauthorized
const FindDeploymentsUnauthorizedCode int = 401

/*FindDeploymentsUnauthorized Authentication information is missing or invalid

swagger:response findDeploymentsUnauthorized
*/
type FindDeploymentsUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewFindDeploymentsUnauthorized creates FindDeploymentsUnauthorized with default headers values
func NewFindDeploymentsUnauthorized() *FindDeploymentsUnauthorized {
	return &FindDeploymentsUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the find deployments unauthorized response
func (o *FindDeploymentsUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *FindDeploymentsUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the find deployments unauthorized response
func (o *FindDeploymentsUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *FindDeploymentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// FindDeploymentsInternalServerErrorCode is the HTTP code returned for type FindDeploymentsInternalServerError
const FindDeploymentsInternalServerErrorCode int = 500

/*FindDeploymentsInternalServerError Internal Server Error

swagger:response findDeploymentsInternalServerError
*/
type FindDeploymentsInternalServerError struct {
}

// NewFindDeploymentsInternalServerError creates FindDeploymentsInternalServerError with default headers values
func NewFindDeploymentsInternalServerError() *FindDeploymentsInternalServerError {
	return &FindDeploymentsInternalServerError{}
}

// WriteResponse to the client
func (o *FindDeploymentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
