// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindImagesHandlerFunc turns a function with the right signature into a find images handler
type FindImagesHandlerFunc func(FindImagesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindImagesHandlerFunc) Handle(params FindImagesParams) middleware.Responder {
	return fn(params)
}

// FindImagesHandler interface for that can handle valid find images params
type FindImagesHandler interface {
	Handle(FindImagesParams) middleware.Responder
}

// NewFindImages creates a new http.Handler for the find images operation
func NewFindImages(ctx *middleware.Context, handler FindImagesHandler) *FindImages {
	return &FindImages{Context: ctx, Handler: handler}
}

/*FindImages swagger:route GET /images findImages

List available images

*/
type FindImages struct {
	Context *middleware.Context
	Handler FindImagesHandler
}

func (o *FindImages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindImagesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
