package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExecutionEnvironmentParams creates a new GetExecutionEnvironmentParams object
// with the default values initialized.
func NewGetExecutionEnvironmentParams() GetExecutionEnvironmentParams {
	var ()
	return GetExecutionEnvironmentParams{}
}

// GetExecutionEnvironmentParams contains all the bound params for the get execution environment operation
// typically these are obtained from a http.Request
//
// swagger:parameters getExecutionEnvironment
type GetExecutionEnvironmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	ExecutionenvironmentID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetExecutionEnvironmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rExecutionenvironmentID, rhkExecutionenvironmentID, _ := route.Params.GetOK("executionenvironmentId")
	if err := o.bindExecutionenvironmentID(rExecutionenvironmentID, rhkExecutionenvironmentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetExecutionEnvironmentParams) bindExecutionenvironmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("executionenvironmentId", "path", "int64", raw)
	}
	o.ExecutionenvironmentID = value

	return nil
}
