package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"omi-gitlab.e-technik.uni-ulm.de/vice/vice-api/models"
)

// GetExecutionEnvironmentOKCode is the HTTP code returned for type GetExecutionEnvironmentOK
const GetExecutionEnvironmentOKCode int = 200

/*GetExecutionEnvironmentOK successful operation

swagger:response getExecutionEnvironmentOK
*/
type GetExecutionEnvironmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.ExecutionEnvironment `json:"body,omitempty"`
}

// NewGetExecutionEnvironmentOK creates GetExecutionEnvironmentOK with default headers values
func NewGetExecutionEnvironmentOK() *GetExecutionEnvironmentOK {
	return &GetExecutionEnvironmentOK{}
}

// WithPayload adds the payload to the get execution environment o k response
func (o *GetExecutionEnvironmentOK) WithPayload(payload *models.ExecutionEnvironment) *GetExecutionEnvironmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get execution environment o k response
func (o *GetExecutionEnvironmentOK) SetPayload(payload *models.ExecutionEnvironment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExecutionEnvironmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetExecutionEnvironmentBadRequestCode is the HTTP code returned for type GetExecutionEnvironmentBadRequest
const GetExecutionEnvironmentBadRequestCode int = 400

/*GetExecutionEnvironmentBadRequest Invalid ID supplied

swagger:response getExecutionEnvironmentBadRequest
*/
type GetExecutionEnvironmentBadRequest struct {
}

// NewGetExecutionEnvironmentBadRequest creates GetExecutionEnvironmentBadRequest with default headers values
func NewGetExecutionEnvironmentBadRequest() *GetExecutionEnvironmentBadRequest {
	return &GetExecutionEnvironmentBadRequest{}
}

// WriteResponse to the client
func (o *GetExecutionEnvironmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetExecutionEnvironmentNotFoundCode is the HTTP code returned for type GetExecutionEnvironmentNotFound
const GetExecutionEnvironmentNotFoundCode int = 404

/*GetExecutionEnvironmentNotFound Execution environment not found

swagger:response getExecutionEnvironmentNotFound
*/
type GetExecutionEnvironmentNotFound struct {
}

// NewGetExecutionEnvironmentNotFound creates GetExecutionEnvironmentNotFound with default headers values
func NewGetExecutionEnvironmentNotFound() *GetExecutionEnvironmentNotFound {
	return &GetExecutionEnvironmentNotFound{}
}

// WriteResponse to the client
func (o *GetExecutionEnvironmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
