package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vice-registry/vice-api/models"
)

// GetDeploymentOKCode is the HTTP code returned for type GetDeploymentOK
const GetDeploymentOKCode int = 200

/*GetDeploymentOK successful operation

swagger:response getDeploymentOK
*/
type GetDeploymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Deployment `json:"body,omitempty"`
}

// NewGetDeploymentOK creates GetDeploymentOK with default headers values
func NewGetDeploymentOK() *GetDeploymentOK {
	return &GetDeploymentOK{}
}

// WithPayload adds the payload to the get deployment o k response
func (o *GetDeploymentOK) WithPayload(payload *models.Deployment) *GetDeploymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get deployment o k response
func (o *GetDeploymentOK) SetPayload(payload *models.Deployment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDeploymentUnauthorizedCode is the HTTP code returned for type GetDeploymentUnauthorized
const GetDeploymentUnauthorizedCode int = 401

/*GetDeploymentUnauthorized Authentication information is missing or invalid

swagger:response getDeploymentUnauthorized
*/
type GetDeploymentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewGetDeploymentUnauthorized creates GetDeploymentUnauthorized with default headers values
func NewGetDeploymentUnauthorized() *GetDeploymentUnauthorized {
	return &GetDeploymentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the get deployment unauthorized response
func (o *GetDeploymentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *GetDeploymentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the get deployment unauthorized response
func (o *GetDeploymentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *GetDeploymentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// GetDeploymentNotFoundCode is the HTTP code returned for type GetDeploymentNotFound
const GetDeploymentNotFoundCode int = 404

/*GetDeploymentNotFound Deployment not found

swagger:response getDeploymentNotFound
*/
type GetDeploymentNotFound struct {
}

// NewGetDeploymentNotFound creates GetDeploymentNotFound with default headers values
func NewGetDeploymentNotFound() *GetDeploymentNotFound {
	return &GetDeploymentNotFound{}
}

// WriteResponse to the client
func (o *GetDeploymentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// GetDeploymentInternalServerErrorCode is the HTTP code returned for type GetDeploymentInternalServerError
const GetDeploymentInternalServerErrorCode int = 500

/*GetDeploymentInternalServerError Internal Server Error

swagger:response getDeploymentInternalServerError
*/
type GetDeploymentInternalServerError struct {
}

// NewGetDeploymentInternalServerError creates GetDeploymentInternalServerError with default headers values
func NewGetDeploymentInternalServerError() *GetDeploymentInternalServerError {
	return &GetDeploymentInternalServerError{}
}

// WriteResponse to the client
func (o *GetDeploymentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
