package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetExecutionEnvironmentHandlerFunc turns a function with the right signature into a get execution environment handler
type GetExecutionEnvironmentHandlerFunc func(GetExecutionEnvironmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetExecutionEnvironmentHandlerFunc) Handle(params GetExecutionEnvironmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetExecutionEnvironmentHandler interface for that can handle valid get execution environment params
type GetExecutionEnvironmentHandler interface {
	Handle(GetExecutionEnvironmentParams, interface{}) middleware.Responder
}

// NewGetExecutionEnvironment creates a new http.Handler for the get execution environment operation
func NewGetExecutionEnvironment(ctx *middleware.Context, handler GetExecutionEnvironmentHandler) *GetExecutionEnvironment {
	return &GetExecutionEnvironment{Context: ctx, Handler: handler}
}

/*GetExecutionEnvironment swagger:route GET /executionenvironment/{executionenvironmentId} getExecutionEnvironment

Get execution environment by id

*/
type GetExecutionEnvironment struct {
	Context *middleware.Context
	Handler GetExecutionEnvironmentHandler
}

func (o *GetExecutionEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetExecutionEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
