// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDeploymentParams creates a new GetDeploymentParams object
// with the default values initialized.
func NewGetDeploymentParams() GetDeploymentParams {
	var ()
	return GetDeploymentParams{}
}

// GetDeploymentParams contains all the bound params for the get deployment operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDeployment
type GetDeploymentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	DeploymentID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetDeploymentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rDeploymentID, rhkDeploymentID, _ := route.Params.GetOK("deploymentId")
	if err := o.bindDeploymentID(rDeploymentID, rhkDeploymentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDeploymentParams) bindDeploymentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DeploymentID = raw

	return nil
}
