package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateExecutionEnvironmentBadRequestCode is the HTTP code returned for type UpdateExecutionEnvironmentBadRequest
const UpdateExecutionEnvironmentBadRequestCode int = 400

/*UpdateExecutionEnvironmentBadRequest Invalid ID supplied

swagger:response updateExecutionEnvironmentBadRequest
*/
type UpdateExecutionEnvironmentBadRequest struct {
}

// NewUpdateExecutionEnvironmentBadRequest creates UpdateExecutionEnvironmentBadRequest with default headers values
func NewUpdateExecutionEnvironmentBadRequest() *UpdateExecutionEnvironmentBadRequest {
	return &UpdateExecutionEnvironmentBadRequest{}
}

// WriteResponse to the client
func (o *UpdateExecutionEnvironmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateExecutionEnvironmentUnauthorizedCode is the HTTP code returned for type UpdateExecutionEnvironmentUnauthorized
const UpdateExecutionEnvironmentUnauthorizedCode int = 401

/*UpdateExecutionEnvironmentUnauthorized Authentication information is missing or invalid

swagger:response updateExecutionEnvironmentUnauthorized
*/
type UpdateExecutionEnvironmentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewUpdateExecutionEnvironmentUnauthorized creates UpdateExecutionEnvironmentUnauthorized with default headers values
func NewUpdateExecutionEnvironmentUnauthorized() *UpdateExecutionEnvironmentUnauthorized {
	return &UpdateExecutionEnvironmentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the update execution environment unauthorized response
func (o *UpdateExecutionEnvironmentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *UpdateExecutionEnvironmentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the update execution environment unauthorized response
func (o *UpdateExecutionEnvironmentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *UpdateExecutionEnvironmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// UpdateExecutionEnvironmentNotFoundCode is the HTTP code returned for type UpdateExecutionEnvironmentNotFound
const UpdateExecutionEnvironmentNotFoundCode int = 404

/*UpdateExecutionEnvironmentNotFound Execution Environment not found

swagger:response updateExecutionEnvironmentNotFound
*/
type UpdateExecutionEnvironmentNotFound struct {
}

// NewUpdateExecutionEnvironmentNotFound creates UpdateExecutionEnvironmentNotFound with default headers values
func NewUpdateExecutionEnvironmentNotFound() *UpdateExecutionEnvironmentNotFound {
	return &UpdateExecutionEnvironmentNotFound{}
}

// WriteResponse to the client
func (o *UpdateExecutionEnvironmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// UpdateExecutionEnvironmentMethodNotAllowedCode is the HTTP code returned for type UpdateExecutionEnvironmentMethodNotAllowed
const UpdateExecutionEnvironmentMethodNotAllowedCode int = 405

/*UpdateExecutionEnvironmentMethodNotAllowed Validation exception

swagger:response updateExecutionEnvironmentMethodNotAllowed
*/
type UpdateExecutionEnvironmentMethodNotAllowed struct {
}

// NewUpdateExecutionEnvironmentMethodNotAllowed creates UpdateExecutionEnvironmentMethodNotAllowed with default headers values
func NewUpdateExecutionEnvironmentMethodNotAllowed() *UpdateExecutionEnvironmentMethodNotAllowed {
	return &UpdateExecutionEnvironmentMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateExecutionEnvironmentMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
