// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-api/models"
)

// UpdateEnvironmentHandlerFunc turns a function with the right signature into a update environment handler
type UpdateEnvironmentHandlerFunc func(UpdateEnvironmentParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateEnvironmentHandlerFunc) Handle(params UpdateEnvironmentParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateEnvironmentHandler interface for that can handle valid update environment params
type UpdateEnvironmentHandler interface {
	Handle(UpdateEnvironmentParams, *models.User) middleware.Responder
}

// NewUpdateEnvironment creates a new http.Handler for the update environment operation
func NewUpdateEnvironment(ctx *middleware.Context, handler UpdateEnvironmentHandler) *UpdateEnvironment {
	return &UpdateEnvironment{Context: ctx, Handler: handler}
}

/*UpdateEnvironment swagger:route PUT /environments updateEnvironment

Update an existing execution environment

*/
type UpdateEnvironment struct {
	Context *middleware.Context
	Handler UpdateEnvironmentHandler
}

func (o *UpdateEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateEnvironmentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
