// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-util/models"
)

// UpdateImageHandlerFunc turns a function with the right signature into a update image handler
type UpdateImageHandlerFunc func(UpdateImageParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateImageHandlerFunc) Handle(params UpdateImageParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateImageHandler interface for that can handle valid update image params
type UpdateImageHandler interface {
	Handle(UpdateImageParams, *models.User) middleware.Responder
}

// NewUpdateImage creates a new http.Handler for the update image operation
func NewUpdateImage(ctx *middleware.Context, handler UpdateImageHandler) *UpdateImage {
	return &UpdateImage{Context: ctx, Handler: handler}
}

/*UpdateImage swagger:route PUT /images updateImage

Update an existing image

*/
type UpdateImage struct {
	Context *middleware.Context
	Handler UpdateImageHandler
}

func (o *UpdateImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateImageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
