package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateExecutionEnvironmentHandlerFunc turns a function with the right signature into a update execution environment handler
type UpdateExecutionEnvironmentHandlerFunc func(UpdateExecutionEnvironmentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateExecutionEnvironmentHandlerFunc) Handle(params UpdateExecutionEnvironmentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateExecutionEnvironmentHandler interface for that can handle valid update execution environment params
type UpdateExecutionEnvironmentHandler interface {
	Handle(UpdateExecutionEnvironmentParams, interface{}) middleware.Responder
}

// NewUpdateExecutionEnvironment creates a new http.Handler for the update execution environment operation
func NewUpdateExecutionEnvironment(ctx *middleware.Context, handler UpdateExecutionEnvironmentHandler) *UpdateExecutionEnvironment {
	return &UpdateExecutionEnvironment{Context: ctx, Handler: handler}
}

/*UpdateExecutionEnvironment swagger:route PUT /executionenvironments updateExecutionEnvironment

Update an existing execution environment

*/
type UpdateExecutionEnvironment struct {
	Context *middleware.Context
	Handler UpdateExecutionEnvironmentHandler
}

func (o *UpdateExecutionEnvironment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateExecutionEnvironmentParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
