package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateEnvironmentBadRequestCode is the HTTP code returned for type UpdateEnvironmentBadRequest
const UpdateEnvironmentBadRequestCode int = 400

/*UpdateEnvironmentBadRequest Invalid ID supplied

swagger:response updateEnvironmentBadRequest
*/
type UpdateEnvironmentBadRequest struct {
}

// NewUpdateEnvironmentBadRequest creates UpdateEnvironmentBadRequest with default headers values
func NewUpdateEnvironmentBadRequest() *UpdateEnvironmentBadRequest {
	return &UpdateEnvironmentBadRequest{}
}

// WriteResponse to the client
func (o *UpdateEnvironmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateEnvironmentUnauthorizedCode is the HTTP code returned for type UpdateEnvironmentUnauthorized
const UpdateEnvironmentUnauthorizedCode int = 401

/*UpdateEnvironmentUnauthorized Authentication information is missing or invalid

swagger:response updateEnvironmentUnauthorized
*/
type UpdateEnvironmentUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewUpdateEnvironmentUnauthorized creates UpdateEnvironmentUnauthorized with default headers values
func NewUpdateEnvironmentUnauthorized() *UpdateEnvironmentUnauthorized {
	return &UpdateEnvironmentUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the update environment unauthorized response
func (o *UpdateEnvironmentUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *UpdateEnvironmentUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the update environment unauthorized response
func (o *UpdateEnvironmentUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *UpdateEnvironmentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// UpdateEnvironmentNotFoundCode is the HTTP code returned for type UpdateEnvironmentNotFound
const UpdateEnvironmentNotFoundCode int = 404

/*UpdateEnvironmentNotFound Environment not found

swagger:response updateEnvironmentNotFound
*/
type UpdateEnvironmentNotFound struct {
}

// NewUpdateEnvironmentNotFound creates UpdateEnvironmentNotFound with default headers values
func NewUpdateEnvironmentNotFound() *UpdateEnvironmentNotFound {
	return &UpdateEnvironmentNotFound{}
}

// WriteResponse to the client
func (o *UpdateEnvironmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// UpdateEnvironmentMethodNotAllowedCode is the HTTP code returned for type UpdateEnvironmentMethodNotAllowed
const UpdateEnvironmentMethodNotAllowedCode int = 405

/*UpdateEnvironmentMethodNotAllowed Validation exception

swagger:response updateEnvironmentMethodNotAllowed
*/
type UpdateEnvironmentMethodNotAllowed struct {
}

// NewUpdateEnvironmentMethodNotAllowed creates UpdateEnvironmentMethodNotAllowed with default headers values
func NewUpdateEnvironmentMethodNotAllowed() *UpdateEnvironmentMethodNotAllowed {
	return &UpdateEnvironmentMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateEnvironmentMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
