// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/vice-registry/vice-util/models"
)

// UploadImageHandlerFunc turns a function with the right signature into a upload image handler
type UploadImageHandlerFunc func(UploadImageParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadImageHandlerFunc) Handle(params UploadImageParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UploadImageHandler interface for that can handle valid upload image params
type UploadImageHandler interface {
	Handle(UploadImageParams, *models.User) middleware.Responder
}

// NewUploadImage creates a new http.Handler for the upload image operation
func NewUploadImage(ctx *middleware.Context, handler UploadImageHandler) *UploadImage {
	return &UploadImage{Context: ctx, Handler: handler}
}

/*UploadImage swagger:route POST /image/{imageId}/file uploadImage

Upload a file as image

*/
type UploadImage struct {
	Context *middleware.Context
	Handler UploadImageHandler
}

func (o *UploadImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUploadImageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
