package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewViceAPI creates a new Vice instance
func NewViceAPI(spec *loads.Document) *ViceAPI {
	return &ViceAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
		ServeError:      errors.ServeError,
		JSONConsumer:    runtime.JSONConsumer(),
		XMLConsumer:     runtime.XMLConsumer(),
		JSONProducer:    runtime.JSONProducer(),
		CreateExecutionEnvironmentHandler: CreateExecutionEnvironmentHandlerFunc(func(params CreateExecutionEnvironmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation CreateExecutionEnvironment has not yet been implemented")
		}),
		DeleteExecutionEnvironmentHandler: DeleteExecutionEnvironmentHandlerFunc(func(params DeleteExecutionEnvironmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation DeleteExecutionEnvironment has not yet been implemented")
		}),
		FindExecutionEnvironmentHandler: FindExecutionEnvironmentHandlerFunc(func(params FindExecutionEnvironmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation FindExecutionEnvironment has not yet been implemented")
		}),
		FindImagesHandler: FindImagesHandlerFunc(func(params FindImagesParams) middleware.Responder {
			return middleware.NotImplemented("operation FindImages has not yet been implemented")
		}),
		GetExecutionEnvironmentHandler: GetExecutionEnvironmentHandlerFunc(func(params GetExecutionEnvironmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation GetExecutionEnvironment has not yet been implemented")
		}),
		UpdateExecutionEnvironmentHandler: UpdateExecutionEnvironmentHandlerFunc(func(params UpdateExecutionEnvironmentParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation UpdateExecutionEnvironment has not yet been implemented")
		}),

		ViceAuthAuth: func(token string, scopes []string) (interface{}, error) {
			return nil, errors.NotImplemented("oauth2 bearer auth (vice_auth) has not yet been implemented")
		},
	}
}

/*ViceAPI API endpoint of the ViCE Image Registry: search, deploy, and import virtual environments from supported execution environments like OpenStack, Docker, or bwLehrpool. */
type ViceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer
	// XMLConsumer registers a consumer for a "application/xml" mime type
	XMLConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ViceAuthAuth registers a function that takes an access token and a collection of required scopes and returns a principal
	// it performs authentication based on an oauth2 bearer token provided in the request
	ViceAuthAuth func(string, []string) (interface{}, error)

	// CreateExecutionEnvironmentHandler sets the operation handler for the create execution environment operation
	CreateExecutionEnvironmentHandler CreateExecutionEnvironmentHandler
	// DeleteExecutionEnvironmentHandler sets the operation handler for the delete execution environment operation
	DeleteExecutionEnvironmentHandler DeleteExecutionEnvironmentHandler
	// FindExecutionEnvironmentHandler sets the operation handler for the find execution environment operation
	FindExecutionEnvironmentHandler FindExecutionEnvironmentHandler
	// FindImagesHandler sets the operation handler for the find images operation
	FindImagesHandler FindImagesHandler
	// GetExecutionEnvironmentHandler sets the operation handler for the get execution environment operation
	GetExecutionEnvironmentHandler GetExecutionEnvironmentHandler
	// UpdateExecutionEnvironmentHandler sets the operation handler for the update execution environment operation
	UpdateExecutionEnvironmentHandler UpdateExecutionEnvironmentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *ViceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ViceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ViceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ViceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ViceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ViceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ViceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ViceAPI
func (o *ViceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.XMLConsumer == nil {
		unregistered = append(unregistered, "XMLConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ViceAuthAuth == nil {
		unregistered = append(unregistered, "ViceAuthAuth")
	}

	if o.CreateExecutionEnvironmentHandler == nil {
		unregistered = append(unregistered, "CreateExecutionEnvironmentHandler")
	}

	if o.DeleteExecutionEnvironmentHandler == nil {
		unregistered = append(unregistered, "DeleteExecutionEnvironmentHandler")
	}

	if o.FindExecutionEnvironmentHandler == nil {
		unregistered = append(unregistered, "FindExecutionEnvironmentHandler")
	}

	if o.FindImagesHandler == nil {
		unregistered = append(unregistered, "FindImagesHandler")
	}

	if o.GetExecutionEnvironmentHandler == nil {
		unregistered = append(unregistered, "GetExecutionEnvironmentHandler")
	}

	if o.UpdateExecutionEnvironmentHandler == nil {
		unregistered = append(unregistered, "UpdateExecutionEnvironmentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ViceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ViceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "vice_auth":

			result[name] = security.BearerAuth(scheme.Name, o.ViceAuthAuth)

		}
	}
	return result

}

// ConsumersFor gets the consumers for the specified media types
func (o *ViceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		case "application/xml":
			result["application/xml"] = o.XMLConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *ViceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ViceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the vice API
func (o *ViceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ViceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/executionenvironments"] = NewCreateExecutionEnvironment(o.context, o.CreateExecutionEnvironmentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/executionenvironment/{executionenvironmentId}"] = NewDeleteExecutionEnvironment(o.context, o.DeleteExecutionEnvironmentHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/executionenvironments"] = NewFindExecutionEnvironment(o.context, o.FindExecutionEnvironmentHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/images"] = NewFindImages(o.context, o.FindImagesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/executionenvironment/{executionenvironmentId}"] = NewGetExecutionEnvironment(o.context, o.GetExecutionEnvironmentHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/executionenvironments"] = NewUpdateExecutionEnvironment(o.context, o.UpdateExecutionEnvironmentHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ViceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *ViceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
