// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ViCE Image Registry
API endpoint of the ViCE Image Registry: search, deploy, and import virtual environments from supported execution environments like OpenStack, Docker, or bwLehrpool.


    Schemes:
      http
    Host: localhost:8080
    BasePath: /v1
    Version: 0.1
    Contact: christopher.hauser@uni-ulm.de

    Consumes:
    - application/json
    - application/xml
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
