package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API endpoint of the ViCE Image Registry: search, deploy, and import virtual environments from supported execution environments like OpenStack, Docker, or bwLehrpool.",
    "title": "ViCE Image Registry",
    "contact": {
      "name": "christopher.hauser@uni-ulm.de"
    },
    "version": "0.1"
  },
  "host": "vice.anyops.org",
  "basePath": "/v1",
  "paths": {
    "/executionenvironment/{executionenvironmentId}": {
      "get": {
        "summary": "Get execution environment by id",
        "operationId": "getExecutionEnvironment",
        "security": [
          {
            "vice_auth": [
              "import_images",
              "deploy_images"
            ]
          }
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "executionenvironmentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ExecutionEnvironment"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Execution environment not found"
          }
        }
      },
      "delete": {
        "summary": "Deletes an execution environment",
        "operationId": "deleteExecutionEnvironment",
        "security": [
          {
            "vice_auth": [
              "import_images",
              "deploy_images"
            ]
          }
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "executionenvironmentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          }
        }
      }
    },
    "/executionenvironments": {
      "get": {
        "summary": "List by user accessible execution environments",
        "operationId": "findExecutionEnvironment",
        "security": [
          {
            "vice_auth": [
              "import_images",
              "deploy_images"
            ]
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "filterManagementlayer",
            "in": "query"
          },
          {
            "type": "string",
            "name": "filterRuntimetechnology",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "An array of accessible execution environments.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ExecutionEnvironment"
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "summary": "Update an existing execution environment",
        "operationId": "updateExecutionEnvironment",
        "security": [
          {
            "vice_auth": [
              "import_images",
              "deploy_images"
            ]
          }
        ],
        "parameters": [
          {
            "description": "Pet object that needs to be added to the store",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ExecutionEnvironment"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Execution Environment not found"
          },
          "405": {
            "description": "Validation exception"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "summary": "Create a new execution environment for authenticated user",
        "operationId": "createExecutionEnvironment",
        "security": [
          {
            "vice_auth": [
              "import_images",
              "deploy_images"
            ]
          }
        ],
        "parameters": [
          {
            "description": "Pet object that needs to be added to the store",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ExecutionEnvironment"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/images": {
      "get": {
        "summary": "List available images",
        "operationId": "findImages",
        "responses": {
          "200": {
            "description": "An array of images.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Image"
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Credentials": {
      "type": "object",
      "properties": {
        "endpoint": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "ExecutionEnvironment": {
      "type": "object",
      "properties": {
        "credentials": {
          "$ref": "#/definitions/Credentials"
        },
        "id": {
          "type": "integer"
        },
        "managementlayer": {
          "$ref": "#/definitions/ManagementLayer"
        },
        "runtimetechnology": {
          "$ref": "#/definitions/RuntimeTechnology"
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    },
    "Image": {
      "type": "object",
      "properties": {
        "content-type": {
          "type": "string",
          "enum": [
            "disk-raw",
            "disk-qcow2",
            "disk-vmdk",
            "docker-file",
            "docker-image",
            "packerfile"
          ]
        },
        "image-type": {
          "type": "string",
          "enum": [
            "implicit",
            "declarative"
          ]
        }
      }
    },
    "ManagementLayer": {
      "type": "object",
      "properties": {
        "software": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "basic",
            "cloudcomputing",
            "containercluster",
            "jobscheduler"
          ]
        },
        "version": {
          "type": "string"
        }
      }
    },
    "RuntimeTechnology": {
      "type": "object",
      "properties": {
        "software": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "virtualmachine",
            "container",
            "application"
          ]
        },
        "version": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "vice_auth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://petstore.swagger.io/api/oauth/dialog",
      "scopes": {
        "deploy_images": "deploy images into execution environments",
        "import_images": "import images from execution environments"
      }
    }
  }
}`))
}
