package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API endpoint of the ViCE Image Registry: search, deploy, and import virtual environments from supported execution environments like OpenStack, Docker, or bwLehrpool.",
    "title": "ViCE Image Registry",
    "contact": {
      "name": "christopher.hauser@uni-ulm.de"
    },
    "version": "0.1"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/environment/{environmentId}": {
      "get": {
        "summary": "Get execution environment by id",
        "operationId": "getEnvironment",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "environmentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Environment"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "description": "Environment not found"
          }
        }
      },
      "delete": {
        "summary": "Deletes an execution environment",
        "operationId": "deleteEnvironment",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "environmentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          }
        }
      }
    },
    "/environments": {
      "get": {
        "summary": "List by user accessible execution environments",
        "operationId": "findEnvironment",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "filterManagementlayer",
            "in": "query"
          },
          {
            "type": "string",
            "name": "filterRuntimetechnology",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "An array of accessible execution environments.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Environment"
              }
            }
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "summary": "Update an existing execution environment",
        "operationId": "updateEnvironment",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Environment"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "description": "Environment not found"
          },
          "405": {
            "description": "Validation exception"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "summary": "Create a new execution environment for authenticated user",
        "operationId": "createEnvironment",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Environment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Environment"
            }
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/image/{imageId}": {
      "get": {
        "summary": "Get an image by id",
        "operationId": "getImage",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "imageId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Image"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "description": "Image not found"
          }
        }
      },
      "delete": {
        "summary": "Deletes an image",
        "operationId": "deleteImage",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "type": "string",
            "name": "imageId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          }
        }
      }
    },
    "/images": {
      "get": {
        "summary": "List available images",
        "operationId": "findImages",
        "responses": {
          "200": {
            "description": "An array of images.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Image"
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "summary": "Create a new image",
        "operationId": "createImage",
        "security": [
          {
            "vice_auth": []
          }
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Image"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Image"
            }
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  },
  "definitions": {
    "Credentials": {
      "type": "object",
      "properties": {
        "endpoint": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Environment": {
      "properties": {
        "credentials": {
          "$ref": "#/definitions/Credentials"
        },
        "id": {
          "type": "string"
        },
        "managementlayer": {
          "$ref": "#/definitions/ManagementLayer"
        },
        "runtimetechnology": {
          "$ref": "#/definitions/RuntimeTechnology"
        },
        "userid": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Image": {
      "type": "object",
      "properties": {
        "content-type": {
          "type": "string",
          "enum": [
            "disk-raw",
            "disk-qcow2",
            "disk-vmdk",
            "docker-file",
            "docker-image",
            "packerfile"
          ]
        },
        "id": {
          "type": "string"
        },
        "image-type": {
          "type": "string",
          "enum": [
            "implicit",
            "declarative"
          ]
        },
        "originEnvironment": {
          "$ref": "#/definitions/Environment"
        },
        "userid": {
          "type": "string"
        }
      }
    },
    "ManagementLayer": {
      "type": "object",
      "properties": {
        "software": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "basic",
            "cloudcomputing",
            "containercluster",
            "jobscheduler"
          ]
        },
        "version": {
          "type": "string"
        }
      }
    },
    "RuntimeTechnology": {
      "type": "object",
      "properties": {
        "software": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "virtualmachine",
            "container",
            "application"
          ]
        },
        "version": {
          "type": "string"
        }
      }
    },
    "User": {
      "properties": {
        "id": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "UnauthorizedError": {
      "description": "Authentication information is missing or invalid",
      "headers": {
        "WWW_Authenticate": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "vice_auth": {
      "type": "basic"
    }
  }
}`))
}
