package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Deployment deployment
// swagger:model Deployment
type Deployment struct {

	// environment Id
	EnvironmentID string `json:"environmentId,omitempty"`

	// environment reference
	EnvironmentReference string `json:"environmentReference,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// imageid
	Imageid string `json:"imageid,omitempty"`

	// userid
	Userid string `json:"userid,omitempty"`
}

// Validate validates this deployment
func (m *Deployment) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
